# Контрольная работа

In [3]:
import pandas as pd

In [5]:
df = pd.read_csv('данные_блокнот.csv', sep = ',')
df

     -1.223,-0.798,-0.867,-0.639,-0.545,-0.412,-0.795,-0.629,-0.547,-0.868,-1.223,-0.879,-0.747,-0.818,-0.671,-0.718,-0.991,-0.778,-0.759,-0.892,-1.223,-0.899,-0.987,-0.75,-0.699,-0.566,-0.911,-0.786,-0.7,-1.015,-1.223,-0.766,-0.555,-0.714,-0.545,-0.587,-0.871,-0.62,-0.568,-0.607,2
0     -1.41,-1.029,-1.013,-0.895,-0.762,-0.676,-1.04...
1     -1.107,-0.649,-0.629,-0.492,-0.367,-0.298,-0.6...
2     -1.27,-0.855,-0.958,-0.707,-0.619,-0.469,-0.87...
3     -1.331,-0.862,-0.761,-0.689,-0.498,-0.361,-0.8...
4     -1.049,-0.632,-0.607,-0.469,-0.381,-0.315,-0.5...
...                                                 ...
5494  -0.775,-0.355,-0.556,-0.172,-0.212,-0.148,-0.4...
5495  -1.166,-0.509,-0.354,-0.25,-0.047,-0.073,-0.51...
5496  -1.203,-0.452,-0.118,-0.243,-0.141,-0.074,-0.4...
5497  -1.107,-0.385,-0.55,-0.236,-0.174,-0.157,-0.53...
5498  -0.804,-0.231,-0.515,-0.0,-0.039,0.022,-0.28,-...

[5499 rows x 1 columns]